### ISSUE TITLE
Use Cases in Tutorial Blank Plots

### ISSUE THREAD

**Issue by Azkabanescapee** [ecohealthalliance/lemis#10]
I originally had R version 3.6.2 and I was able to download the dataset and everything seemed to work, up until when I went through the Use Cases questions in the tutorial. The first question about "What kind of animals are being imported through Sault Sainte Marie?" worked fine, but I am consistently getting blank plots (x and y-axis labels are there but no data is plotted) for all the other questions. Believing it had something to do with Incompatibilities, I updated R to v4.0.0 and this then led to new problems (could not download the dataset anymore). Thanks to your suggested solution of downgrading dplyr, I managed to get it to work again (and I have Windows), but the plots are still all empty. All packages have been downloaded and the code is being followed, so I am unsure why this is happening? 

![image](https://user-images.githubusercontent.com/59973248/83811000-0309ef80-a687-11ea-9820-571f88ddadc1.png)

**Comment by eveskew** [comment]
Hi there, thanks for the inquiry.

Frankly, the vignette is not really the best reference for `lemis` package usage. It has not been substantially updated in quite a while, and I would refer you instead to the [package README](https://github.com/ecohealthalliance/lemis) code and [the data manuscript](https://www.nature.com/articles/s41597-020-0354-5) for explanation of proper data usage.

That said, I do get working plots with R 4.0.0 and the package vignette code. So I'm not totally sure what the problem might be on your end. But if you can run:
```
library(lemis)
library(dplyr)

l <- lemis_data() %>% collect()
dim(l)
```
and get a result that shows `l` has 551,2706 rows and 28 columns, you have all the data as expected. So no need to worry if that's the case.
