### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by PrincessPi314** [ecohealthalliance/lemis#11]
Hello, I would like to use the lemis package for a scientific research project, can you recommend me how to best cite the package? I love the package btw, thanks so much for making this available to the scientific community.

**Comment by noamross** [comment]
Glad this is useful to you! Please cite the associated paper:

> Eskew, E.A., White, A.M., Ross, N. et al. United States wildlife and wildlife product imports from 2000–2014. Sci Data 7, 22 (2020). https://doi.org/10.1038/s41597-020-0354-5
