### ISSUE TITLE
Error in datastorr_auth

### ISSUE THREAD

**Issue by ocstringham** [ecohealthalliance/lemis#8]
I am trying to download the lemis data from the _lemis_ package. I ran this code:

```r
library(lemis)
library(dplyr)

all_lemis <- lemis_data() %>% 
  collect()
```

Then I successfully authenticated in GitHub, but received this error message: 

"Error in datastorr_auth(private, token_only = TRUE) : 
  GitHub token not found; please see ?datastorr_token"

Any ideas on how to proceed?

**Comment by eveskew** [comment]
Hi Oliver. You've made sure to store your GitHub personal access token locally in your `.Renviron` file according to the instructions here: https://happygitwithr.com/github-pat.html#step-by-step? If so, you might just need to restart R to properly load those local environment variables.
